### ISSUE TITLE
Update node types when application is started

### ISSUE THREAD

**Issue by asilev** [doug-101/TreeLine#1]
I'm using treeline as a task manager.
One of my favorite features in a task manager is the ability to snooze (postpone) a task to certain date when it is blocked, so it does not bother me.
I've found a great way to do that in treeline using conditional types.
I create a field for the future date I want the task to be active at, and then I use conditional types to turn the type from blocked to active (each with a different icon, to indicate its state).
The problem is that the conditional types' conditions are tested only when they are actively changed (i.e., a change in one of the fields). This can be resolved if the conditions will also be tested when I start the application, or click a "refresh" button.
I think refresh or testing conditions on application startup would be a great feature as this can resolve conditions that are time dependent, such as this.

Thanks,

**Comment by doug-101** [comment]
I'm leaning toward adding an update/refresh command.  It's more versatile than doing the update at file load and it doesn't slow opening files.

-Doug

**Comment by asilev** [comment]
I agree,
I think it would help a lot.

Thanks!
Great application!

**Comment by doug-101** [comment]
Added Regenerate References command to the Data menu in the beta branch
