### ISSUE TITLE
German legal numbering not supported

### ISSUE THREAD

**Issue by TeresaM12** [doug-101/TreeLine#10]
German legal numbering starts in certain heading levels (level 5 and 8) with double characters. Treeline supports single letter numbering which will after 26 numbers go to double identical character numbering.
It seems not to be defined what happens with more than 26 levels either with the single or the double chracter headings in the German legal numbering. 
The change should not break the numbering behaviour for single character numbering  as implemented now.

Example (only heading levels 1-5): 
```
A. level 1
   I. level 2
    1. level 3
      a) level 4
        aa) level 5 1.<- here
        bb) level 5 2.
      b) level 4 
```
see PR #9

**Comment by doug-101** [comment]
Merged this pull request
