### ISSUE TITLE
Question: Is it possible to use the Type/Format and UID in the Output?

### ISSUE THREAD

**Issue by kghenderson** [doug-101/TreeLine#15]
I'd like to include the Type of the Current Node in the Output, but I can't seem to find the right syntax. 
For example, I'd like a field called 'Kind' which is the Current Type/Format of the Node.

The Type/Format and UID are not in the Fields list, but I'd like to reference them if possible.

e.g. in output, something like: 
```
Name: {*Name*}
Kind: {*!Type*}
```

Thanks.

**Comment by doug-101** [comment]
Currently, there is no way to embed the UID in the output.

But can't you just hard-code the Type, without using a field?  It could be hard-coded differently for each node type.  The only downside I see offhand is that it wouldn't automatically update if a node type is renamed or copied.

-Doug
