### ISSUE TITLE
ChildTypeLimits can not be reset to "All type available"

### ISSUE THREAD

**Issue by asamarco** [doug-101/TreeLine#16]
Hello,

I report that if "ChildTypeLimits" were previously set in Type Config they can not be reset to "[All type Available]" by unchecking all the flags.
It appears to be working at the GUI level but if you try to actually change the type of a child in the tree you will find you still have the same limits as before.

The only workaround I found is to remove manually the childtypelimit entry in the JSON file with a text editor

Treeline 3.1.5
Library versions:
Python: 3.10.6
Qt: 5.15.2
PyQt: 5.15.7
OS: Windows-10-10.0.19045-SP0

**Comment by doug-101** [comment]
A fix for this was committed.
