### ISSUE TITLE
Child count output breaks dynamic HTML export

### ISSUE THREAD

**Issue by asamarco** [doug-101/TreeLine#17]
Hello,

I report that exported live tree view HTML files have nodes with blank output if they employ "child count" reference in their output configuration. I attach a modified version of sample_other_fields with this feature and the HTML it produces. In the latter you will notice that both Parent Info and Child Info nodes can not be opened.

[sample_other_fields+childscount.zip](https://github.com/doug-101/TreeLine/files/10840784/sample_other_fields%2Bchildscount.zip)

Thanks,

Treeline 3.1.5
Library versions:
Python: 3.10.6
Qt: 5.15.2
PyQt: 5.15.7
OS: Windows-10-10.0.19045-SP0

**Comment by doug-101** [comment]
Fixed in today's commit.
