### ISSUE TITLE
Treat fields as zero bug report

### ISSUE THREAD

**Issue by asilev** [doug-101/TreeLine#2]
When unchecking "treat blank fields as zero" and saving the file, I get the error message:

> "A serious error has occurred. Treeline could be in an unstable state..."
> When:  2018-10-03 10:24:26.754704
> TreeLine Version:  3.0.0
> Python Version:  3.6.4
> Qt Version:  5.11.1
> PyQt Version:  5.11.2
> OS:  Windows-7-6.1.7601-SP1
> 
> Traceback (most recent call last):
>   File "C:\git\treeline\devel\source\treelocalcontrol.py", line 742, in fileSave
>   File "C:\git\treeline\devel\source\treestructure.py", line 100, in fileData
> UnboundLocalError: local variable 'fileData' referenced before assignment

Thanks

**Comment by asilev** [comment]
This issue may be a result of using sum math function on children reference, where some of the children contain blank values.

**Comment by doug-101** [comment]
This was an easy fix - it was just a stupid refactoring mistake.

I pushed the fix to the GitHub master branch.

Thanks for the bug report.

-Doug
