### ISSUE TITLE
Checkable items

### ISSUE THREAD

**Issue by chowbok** [doug-101/TreeLine#3]
Would it be possible to make a todo list type with checkboxes, where checking on an item would automatically check the box and change its node type to "TASK_DONE"?

**Comment by doug-101** [comment]
I've thought about that, but I'm not sure how to cleanly implement it.  For performance reasons, I don't want to burden the tree view with so many check boxes.  But a check box wouldn't fit very well with the data-edit view editors.  Any alternate ideas?

I assume that you son't want to use the choice data-edit pull downs from the to-do sample file.  As a current work-around, you could remove the conditional types and use the Set Node Type command on tree view nodes to manually set the type.  It would be fairly quick if done using the ctrl-T shortcut.

-Doug

**Comment by l-arnold** [comment]
Checkboxes would be helpful.
I have used Bonsai and Outliner (Android) together.  Both use checkboxes well.
Outliner supports Treeline synch so it would be pretty nice to have that level of integration.
Bonsai is pretty much lost to the 4 winds now but it still works well.
