### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by rodolfoap** [doug-101/TreeLine#4]
Thanks for version 3, just found it! But I work with ALL black backgrounds and green foregrounds. Can't find that option in this version. How do I change the background colors? I use LXDE, my default options are fine. Thanks.

**Comment by doug-101** [comment]
I removed the color selection from recent versions because it did not work consistently with various themes.

I'm not sure what packages LXDE has available, but you could search for Qt5 settings/themes or for ways to get Qt5 applications to match GTK themes.

**Comment by washere** [comment]
Most apps on various platfroms offer Dark and/or Black themes.

Most coders, graphics workers, CGI Workstations (in light controlled rooms), data input staff etc. etc. all of whom work long hours use dark or black themed systems.

Apart from flicker-free, long battery on laptops etc the benefit of a dark theme is one can work longer hours, with less stress and more efficiently without staring into a light-box (white background monitor) at close distance.

For hours on end, day after day, year after year, decade after decade, staring into a flat light source close-up intensely, chasing pixels to work with. Even Microsoft finally gave us dark explorer windows a few months ago in the latest dark apps theme.

Many professionals simply do not use non-Dark/black theme apps. I am one of them.

It is a must these days and future generations will laugh how billions stared into a light-box close-up during the working lifetime.

Best wishes.

https://www.instagram.com/worldcode/

https://www.instagram.com/programmerrepublic/

**Comment by doug-101** [comment]
I'll look into it again when I have some time.  The program had the feature several years ago, but, at that time, it was not very consistent.

**Comment by doug-101** [comment]
OK, a dark theme is now available in the new 3.1.0 release.  Let me know what you think.

-Doug
