### ISSUE TITLE
Set Node Type issue?

### ISSUE THREAD

**Issue by sttrebo** [doug-101/TreeLine#5]
quick question:  The SetNodeType command doesn't seem to do anything for me.  I select an item and hit "Data" "SetNodeType" then "ActivityFinished".  Nothing seems to happen.  Same if I try and change an item to unfinished.  Am I missing something?

thanks
steve

**Comment by doug-101** [comment]
Are you using a variation of the to-do list samples?  They use an advanced feature called conditional types, where the type is automatically set based on some conditions that depend on the node data.  In that case, manually setting the feature type doesn't work.
