### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by crashr** [doug-101/TreeLine#6]
Hello. 
Great tool. Thanks. but what happened to the plugin interface? Are plugins still supported at all in recent version? 
And where to download samples for older versions? Couldn't find a link on your website.

**Comment by doug-101** [comment]
crashr wrote:
> Hello. 
> Great tool. Thanks. but what happened to the plugin interface? Are plugins still supported at all in recent version? 

No, recent versions no longer support plugins.  A plugin interface would
be labor intensive to implement and would add some overhead to many
TreeLine operations.  More importantly, the plugin system never became
as useful as I had hoped.  I can't recall a single instance where a user
created a plugin and made it available to other users.

> And where to download samples for older versions? Couldn't find a link on your website.

They can be downloaded from the TreeLine files area on Sourceforge.

Thanks,
Doug

**Comment by crashr** [comment]
Bad news. But I understand that. So I have to dig into your code on my own.
