### ISSUE TITLE
Math Fields broken in recent Python version

### ISSUE THREAD

**Issue by HeirOfNorton** [doug-101/TreeLine#7]
Hello. I am using TreeLine on Arch Linux with the system Python version 3.81. I try to make a Math field on a Node, and when I try to save the equation, no matter what I have put into it, I get an error message:

```
Illegal object type or operator: Constant
```

This happens even if the equation is nothing more than `1 + 1`.

Recent versions of Python added the `Constant` class to the `ast` module as an optimization. Not sure why it would be causing issues now, since it was added in 3.6. Adding `Constant` to the `allowedNodeTypes` set in matheval.py seems to fix it, but I don't know if this will cause any other problems down the road.

Thanks!

**Comment by doug-101** [comment]
HeirOfNorton wrote:
> Hello. I am using TreeLine on Arch Linux with the system Python
> version 3.81. I try to make a Math field on a Node, and when I try to
> save the equation, no matter what I have put into it, I get an error
> message:
> 
> ``` Illegal object type or operator: Constant ```
> 
> This happens even if the equation is nothing more than `1 + 1`.
> 
> Recent versions of Python added the `Constant` class to the `ast`
> module as an optimization. Not sure why it would be causing issues
> now, since it was added in 3.6. Adding `Constant` to the
> `allowedNodeTypes` set in matheval.py seems to fix it, but I don't
> know if this will cause any other problems down the road.

It's OK to add it. Apparently it was made available in 3.6, but just
started being generated by the parser in 3.8.  

I'm also adding "NameConstant" (addedin 3.4), even though it's
deprecated in 3.8.  It doesn't hurt to have extra types in the set, and
some version of Python might want to see it.

Thanks for the thorough bug report!

-Doug
